// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlgen

import (
	"time"
)

type Item struct {
	ID             string
	SubscriptionID string
	GoodwillID     int64
	CreatedAt      time.Time
	AuctionEndAt   time.Time
}

type Subscription struct {
	ID             string
	UserID         string
	Term           string
	MinPrice       *int64
	MaxPrice       *int64
	CategoryID     *int64
	LastNotifiedAt time.Time
}
