// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlgen

import (
	"context"
)

type Querier interface {
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	DeleteExpiredItems(ctx context.Context) (int64, error)
	DeleteUserSubscriptions(ctx context.Context, arg DeleteUserSubscriptionsParams) error
	FindItemInSubscription(ctx context.Context, arg FindItemInSubscriptionParams) (Item, error)
	FindItemsEndingSoon(ctx context.Context) ([]Item, error)
	FindSubscription(ctx context.Context, id string) (Subscription, error)
	FindSubscriptionsToNotify(ctx context.Context) ([]Subscription, error)
	FindUserSubscriptions(ctx context.Context, userID string) ([]Subscription, error)
	SetItemSentFinal(ctx context.Context, ids []string) error
	SetSubscriptionLastNotifiedAt(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
