// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlgen

import (
	"context"
	"time"
)

type Querier interface {
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	DeleteUserSubscriptions(ctx context.Context, arg DeleteUserSubscriptionsParams) error
	FindItemInSubscription(ctx context.Context, arg FindItemInSubscriptionParams) (Item, error)
	FindItemsEndingSoon(ctx context.Context, auctionEndAt time.Time) ([]Item, error)
	FindUserSubscriptions(ctx context.Context, userID string) ([]Subscription, error)
}

var _ Querier = (*Queries)(nil)
